### ISSUE TITLE
Document ports

### ISSUE THREAD

**Issue by abrkn** [drivechain-project/bitcoin#100]
![image](https://user-images.githubusercontent.com/843958/46247828-3371a300-c43b-11e8-9f3a-2614992f1de0.png)

It's currently tough to look up/memorize what ports are used for what (main/side, rpc/p2p).

Please make a wiki with a table of default port settings.

**Comment by CryptAxe** [comment]
https://github.com/DriveNetTESTDRIVE/docs/blob/master/PortNumbers.md
