### ISSUE TITLE
Nit: Change default branch on this project

### ISSUE THREAD

**Issue by Christewart** [drivechain-project/bitcoin#17]
Can we change the default branch to `mainchainBMM` for this repo? This is what people are looking for when then come to this repo IMO.

**Comment by CryptAxe** [comment]
I thought about this for a while and don't have any strong feelings one way or another. I think that it is important for people to at least know that there is a testing sidechain that already exists. The mainchainBMM code however is all that will need to be merged upstream, so maybe that should be the master branch... What do you think @psztorc?

**Comment by psztorc** [comment]
I agree that mainchainBMM should be a the default. The default should be the changes we are proposing to the existing Bitcoin software.

**Comment by CryptAxe** [comment]
Changed default branch to mainchainBMM
