### ISSUE TITLE
BMM Linking data map (part of ratchet system) should be changed to std::map, no need for std::multimap

### ISSUE THREAD

**Issue by CryptAxe** [drivechain-project/bitcoin#19]
See here: https://github.com/drivechain-project/bitcoin/blob/mainchainBMM/src/sidechaindb.h#L89

Initially the mapBMMLD chosen was a std::multimap. This is unnecessary as a block which competes with another for the same height _must_ have a different hash. So mapBMMLD's container should be changed to std::map<uint256, int>.

**Comment by ghabs** [comment]
This bug looks like it can be closed as obsolete, as the multimap has already been refactored out.

**Comment by CryptAxe** [comment]
That is correct, thank you sir!
