### ISSUE TITLE
Build failed with no matching function for call to ‘ReadBlockFromDisk(CBlock&, const CBlockIndex*&, const Consensus::Params&)’

### ISSUE THREAD

**Issue by andrewmilson** [drivechain-project/bitcoin#25]
Have installed all nessesary dependencies listed in doc/build-unix.md for Ubuntu. Can successfully build the 'mainchainBMM' branch although am getting the following build error on the 'sidechainBMM' branch.

```
$ ./autogen.sh
$ ./configure
$ make
...
zmq/zmqpublishnotifier.cpp: In member function ‘virtual bool CZMQPublishRawBlockNotifier::NotifyBlock(const CBlockIndex*)’:
zmq/zmqpublishnotifier.cpp:174:61: error: no matching function for call to ‘ReadBlockFromDisk(CBlock&, const CBlockIndex*&, const Consensus::Params&)’
         if(!ReadBlockFromDisk(block, pindex, consensusParams))
                                                             ^
In file included from zmq/zmqpublishnotifier.cpp:8:0:
./validation.h:484:6: note: candidate: bool ReadBlockFromDisk(CBlock&, const CDiskBlockPos&)
 bool ReadBlockFromDisk(CBlock& block, const CDiskBlockPos& pos);
      ^
./validation.h:484:6: note:   candidate expects 2 arguments, 3 provided
./validation.h:485:6: note: candidate: bool ReadBlockFromDisk(CBlock&, const CBlockIndex*)
 bool ReadBlockFromDisk(CBlock& block, const CBlockIndex* pindex);
      ^
./validation.h:485:6: note:   candidate expects 2 arguments, 3 provided
Makefile:6142: recipe for target 'zmq/libbitcoin_zmq_a-zmqpublishnotifier.o' failed
make[2]: *** [zmq/libbitcoin_zmq_a-zmqpublishnotifier.o] Error 1
make[2]: Leaving directory '/home/.../drivechain/src'
Makefile:9031: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/.../drivechain/src'
Makefile:686: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
``` 

- OS: Ubuntu 16.04.1 LTS x86_64

**Comment by CryptAxe** [comment]
I just compiled on Ubuntu 16.10

**Comment by CryptAxe** [comment]
I just compiled on Ubuntu 16.10, try double checking that you have all of the dependencies installed:


```
# Install bitcoin deps
sudo apt-get install \
    automake \
    autotools-dev \
    bsdmainutils \
    build-essential \
    libboost-all-dev \
    libdb++-dev \
    libevent-dev \
    libssl-dev \
    libtool \
    pkg-config

# Install bitcoin GUI deps
sudo apt-get install \
    libprotobuf-dev \
    libqrencode-dev \
    libqt5core5a \
    libqt5dbus5 \
    libqt5gui5 \
    protobuf-compiler \
    qttools5-dev \
    qttools5-dev-tools

# Install bitcoin compatible bdb from PPA
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev
```


Let me know if you still have issues and we'll try and figure it out. I'm also opening up an issue right now about fixing some unit tests and a few of the builds that are failing https://travis-ci.org/drivechain-project/bitcoin/builds/245122229 and we'll see if your issue is related. 

Thanks!

**Comment by andrewmilson** [comment]
Made sure I had installed all the dependencies you listed above. Still getting the same error!

**Comment by CryptAxe** [comment]
Are you able to compile bitcoin core on that system?

**Comment by andrewmilson** [comment]
yes

**Comment by CryptAxe** [comment]
Alright @andrewmilson if you get the chance to pull the code and try again please let me know if you still have the same issue. A few build errors have been fixed including the one that you have reported. We should be able to close this issue and keep https://github.com/drivechain-project/bitcoin/issues/26 open until all of the tests are passing on Travis CI. Thanks!

**Comment by CryptAxe** [comment]
I'm going to close this because I managed to confirm for myself that the build is working now in Ubuntu 16.04.1. If you ever get a chance to test again and have any issues, let me know! The other issue regarding build errors in general will remain open.
