### ISSUE TITLE
Should BMM tests be moved into their own file?

### ISSUE THREAD

**Issue by CryptAxe** [drivechain-project/bitcoin#34]
Currently the blind merged mining tests are at the bottom of the SidechainDB unit test file ```src/test/sidechaindb_tests.cpp``` Should they be moved into a separate file to keep things organized?

**Comment by Christewart** [comment]
I think if we are thinking about doing this now, we should do it. It doesn't seem like a obvious place to have them in `sidechaindb_tests.cpp`

**Comment by CryptAxe** [comment]
Moved
