### ISSUE TITLE
Make throws undefined symbol error related to CPartialMerkleTree

### ISSUE THREAD

**Issue by Sjors** [drivechain-project/bitcoin#39]
The following happens on the `sidechainBMM` branch, but not the `v0.14.0` tag.

I'm using macOS 10.12.6.

First I ran autogen and configure as follows:

```
./autogen
./configure --without-gui # same result without that flag
```

Then I run `make check`:
```
Making check in src
  CXXLD    libbitcoinconsensus.la
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "CPartialMerkleTree::CPartialMerkleTree()", referenced from:
      SidechainDeposit::SidechainDeposit() in libbitcoinconsensus_la-sidechain.o
  "memory_cleanse(void*, unsigned long)", referenced from:
      SidechainObj::GetScript() const in libbitcoinconsensus_la-sidechain.o
      SidechainObjCtr(CScript const&) in libbitcoinconsensus_la-sidechain.o
      std::__1::vector<char, zero_after_free_allocator<char> >::vector<char const*>(char const*, std::__1::enable_if<(__is_forward_iterator<char const*>::value) && (is_constructible<char, std::__1::iterator_traits<char const*>::reference>::value), char const*>::type) in libbitcoinconsensus_la-sidechain.o
      std::__1::enable_if<(__is_forward_iterator<char const*>::value) && (is_constructible<char, std::__1::iterator_traits<char const*>::reference>::value), std::__1::__wrap_iter<char*> >::type std::__1::vector<char, zero_after_free_allocator<char> >::insert<char const*>(std::__1::__wrap_iter<char const*>, char const*, char const*) in libbitcoinconsensus_la-sidechain.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbitcoinconsensus.la] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

Should I just use a Linux VM?

**Comment by Sjors** [comment]
When I run `make` on the v0.14.0 tag and then switch to the `sidechainBMM` branch, `make check` does work (although 1 test fails).

Maybe you need to reorder something in Makefile.am?

**Comment by Sjors** [comment]
Although I can make a Sidechain deposit address, entering `generate 1` in the console  (as per the demo video) results in `Method not found (code -32601)`, so I suspect something didn't compile correctly.

**Comment by Sjors** [comment]
`make` does work on Debian 9, though working with a VM is a bit of a pain, so hopefully this is easy to fix for the Mac.

**Comment by CryptAxe** [comment]
Thanks for reporting, this seems to be related to: https://github.com/drivechain-project/bitcoin/issues/26 

Unfortunately the mac builds are not working for the sidechain branch right now as you have found. I wouldn't put a lot of effort into fixing it as big things are still changing over there and I'm 99% sure we are going to end up taking the good code from that repository and rebase with upstream bitcoin core fairly soon.

As for the generate rpc command issue, that video was made before BMM existed and now you have to use the BMM process to create blocks on the sidechain. It is possible to trick the sidechain into thinking the mainchain has applied work to an h* and create blocks but it's fairly complicated..

**Comment by CryptAxe** [comment]
I opened up https://github.com/drivechain-project/drivechain.info/issues/3 noting that we need to update the demo video on the website. 

I'm going to close this issue since we already have it covered by #26 but thank you for reporting it!
