### ISSUE TITLE
Rebase & Fix travis CI builds.

### ISSUE THREAD

**Issue by CryptAxe** [drivechain-project/bitcoin#42]
See: https://travis-ci.org/drivechain-project/bitcoin/builds/245123579

All but one of the travis builds have stopped working, including for the unchanged master branch. Looks like we have to update something to keep working with Travis CI. Upstream have probably already had to do this.

**Comment by CryptAxe** [comment]
Mainchain & Sidechain both need rebase

**Comment by ghabs** [comment]
I've started the rebase on the mainchainBMM branch:
https://github.com/ghabs/bitcoin/tree/rebased

It's pretty messy, mostly because of the CCoin to Coin commit, and I haven't finished updating coin_tests.cpp, but this does currently build.

**Comment by CryptAxe** [comment]
Closing this, we will keep track with: 

https://github.com/drivechain-project/bitcoin/issues/29
https://github.com/drivechain-project/bitcoin/issues/30
