### ISSUE TITLE
Cannot generate blocks in sidechain build

### ISSUE THREAD

**Issue by carlton355** [drivechain-project/bitcoin#48]
Built and setup mainchain and sidechain builds. Started both and sent a deposit transaction.  However when I go to the sidechain Debug window -> console there is no available 'generate' command and if I type 'generate 101' I get 'Method not found code -32601'.

The UI is Blue and I get [regtest].  I started with the --datadir= arg.  The seems correct as it is switching to regtest blue mode so it must be picking up the conf file.

**Comment by psztorc** [comment]
We talked somewhere else, right? This is because (it seems to me), under blind merged mining, the sidechain doesn't really generate its own blocks.

**Comment by CryptAxe** [comment]
You'll actually need to go through the entire process of BMM to get blocks to generate on the sidechain node. Stay tuned for an updated guide on how to do this!
