### ISSUE TITLE
Remove wait period and update verification period to match specifications in docs

### ISSUE THREAD

**Issue by CryptAxe** [drivechain-project/bitcoin#68]

**Comment by ghabs** [comment]
What's the wait period? I'm assuming this isn't for the sidechain to mainchain move, where the wait seems like a necessary condition to prevent fraud? Unless your intention is to create a fork that would better demonstrate the potential w/o people having to wait six months?

**Comment by CryptAxe** [comment]
It is a period of blocks  after a sidechain withdrawal WT^ has been seen before it is allowed to be voted on. https://github.com/drivechain-project/bitcoin/blob/mainchainBMM/src/sidechain.h#L25 
@psztorc and I have briefly talked about removing it so I made it an issue for discussion. I think we should remove it.

**Comment by CryptAxe** [comment]
The wait period should be removed, and a universal 6 month verification period set.

**Comment by CryptAxe** [comment]
https://github.com/drivechain-project/bitcoin/pull/84
