### ISSUE TITLE
hi  how to use the BMM button on the GUI?

### ISSUE THREAD

**Issue by mycamphortree** [drivechain-project/bitcoin#89]
I compiled the latest version of the program on March 23, 2018. However, it seems that the method provided by "http://www.drivechain.info/" does not apply to the latest version. So, where is the latest version description? Or how to use the BMM button on the GUI?

**Comment by CryptAxe** [comment]
Could you tell me which specific page on the website you're looking at
which has outdated information?

If you are on the BMM page of the sidechain client there is just a generate
BMM button which will output the information required by the mainchain, and
store the BMM block on the sidechain client. Is that part working for you?

**Comment by mycamphortree** [comment]
The "Demo Video" (https://drive.google.com/file/d/0B0apsclL6jccNEViRy00TThJd2M/view) of your website homepage should not be the latest version.

The latest version of the "sidechainBMM" program has more BMM interfaces than the original "sidechain". However, I clicked on the "Generate Block" error and quit the program.
Displayed on the terminal:
     EXCEPTION: St13runtime_error
     CreateNewBlock: TestBlockValidity failed: bad-critical-hash, invalid critical hash proof

In addition, when using the latest version of the program, can it be understood that the "Generate Block" button on the "sidechainBMM" interface replaces the "generate xx" command of the original "sidechain", and the remaining operations and the operations provided by "Demo Video" are Consistent?

**Comment by HLNaima** [comment]
Hello,

It's the same here. Both clicking on "Generate Block" and running the "generate" RPC command give the same error : `CreateNewBlock: TestBlockValidity failed: bad-critical-hash, invalid critical hash proof (code 16)`.

I tried following the steps provided in the testing repo [here](https://github.com/drivechain-project/testing) (That is outdated by the way).

**Comment by CryptAxe** [comment]
Hey guys please check out the guide to use the latest version, please let us know if you have any issues! All of this should work for you now. 

http://www.drivechain.info/blog/usage-tour/
