### ISSUE TITLE
[trivial] Update SidechainDB class name in line with bitcoin-core style

### ISSUE THREAD

**Issue by CryptAxe** [drivechain-project/bitcoin#9]
SidechainDB should be renamed CSidechainDB

**Comment by joemphilips** [comment]
Should "SCDB" renamed to CSCDB too?

**Comment by CryptAxe** [comment]
No just the class name should change and all of the instances can still be called SCDB / scdb. So in validation.cpp:
https://github.com/drivechain-project/bitcoin/blob/mainchainBMM/src/validation.cpp#L91

instead of 
SidechainDB scdb; 

it should be 
CSidechainDB scdb;

And https://github.com/drivechain-project/bitcoin/blob/mainchainBMM/src/sidechaindb.h#L80-L81 can stay how it is. 

It's probably confusing that I named the internal data structure within sidechaindb.cpp SCDB and then named the instance of the class that gets used by validation scdb. I'm open to suggestions on renaming it.. did you find that confusing?

**Comment by joemphilips** [comment]
I got it. Sorry for stupid question.
This one seems to be good starting point for me to learn C++, so let me handle it.

**Comment by CryptAxe** [comment]
No not stupid at all, thank you for helping!
